### ISSUE TITLE
How to verify if date is available

### ISSUE THREAD

**Issue by raghav-commits** [AnotherSava/usvisa-appointment-finder#3]
I changed the latest_notification_date=2023-10-01 to 2025-02-11(current appointment availability in the site) to check if I will be getting the message on the terminal or message on telegram that thhe date is available. But I dint get any. Not sure if the code is working for me correctly. Please can you help me out or clarify what should I change to check if code is working fine.

**Comment by lucasudar** [comment]
solved with @raghav-commits. he entered wrong config values
